LangString addOrReinstall ${LANG_POLISH} "Dodaj lub zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "GreekGod jest już zainstalowany"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowany. Wybierz działanie i kliknij Dalej."
LangString appRunning ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiony. Zamknij aplikację i spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiony.$\nKliknij OK, aby go zamknąć."
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz działanie konserwacyjne."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz sposób instalacji ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (obniżenie wersji bez odinstalowania jest wyłączone)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zamknąć ${PRODUCTNAME}. Zamknij aplikację i spróbuj ponownie."
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2…"
LangString newerVersionInstalled ${LANG_POLISH} "Na komputerze jest zainstalowana nowsza wersja ${PRODUCTNAME}. Przed instalacją starszej wersji zalecane jest odinstalowanie obecnej."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "Na komputerze jest zainstalowana $R4 wersja ${PRODUCTNAME}. Instalacja będzie kontynuowana w bieżącej lokalizacji."
LangString silentDowngrades ${LANG_POLISH} "Obniżanie wersji jest wyłączone dla instalacji cichej.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie udało się odinstalować aplikacji."
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2. Uruchom instalator ponownie."
LangString webview2DownloadError ${LANG_POLISH} "Nie udało się pobrać WebView2: $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pobrano WebView2"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie WebView2…"
LangString webview2InstallError ${LANG_POLISH} "Instalacja WebView2 zakończyła się kodem $1"
LangString webview2InstallSuccess ${LANG_POLISH} "Zainstalowano WebView2"
LangString deleteAppData ${LANG_POLISH} "Usuń dane aplikacji"
